defaults:
  - _self_
  - task: lift_graph
  - policy: egnn_policy

render: True
output_video: True

num_episodes: 20
max_steps: ${task.max_steps}
output_dir: ./outputs
load_ckpt: True


pred_horizon: 16
obs_horizon: 2
action_horizon: 8


env_runner: ${task.env_runner}


seed: 0

agent:
  _target_: imitation.agent.robomimic_lowdim_agent.RobomimicLowdimAgent
  env: ${task.env_runner}
  