defaults:
  - _self_
  - task: lift_lowdim
  - policy: mlp_policy

render: False
output_video: True

num_episodes: 20
max_steps: 500
output_dir: ./outputs


pred_horizon: 8
obs_horizon: 4
action_horizon: 8


env_runner: ${task.env_runner}


seed: 0

agent:
  _target_: imitation.agent.robomimic_lowdim_agent.RobomimicLowdimAgent
  env: ${task.env_runner}