num_episodes: 2
max_steps: 1000
output_dir: ./output


env_runner: 
  _target_: imitation.env_runner.robomimic_lowdim_runner.RobomimicEnvRunner
  output_dir: ${output_dir}
  env:
    _target_: imitation.env.kitchen_pose.gym_kitchen_wrappers.KitchenPoseWrapper
policy:
  _target_: imitation.policy.random_policy.RandomPolicy

agent:
  _target_: imitation.agent.robomimic_lowdim_agent.RobomimicLowdimAgent