num_episodes: 5
output_dir: ./output

# Environment
obs_dim: 6
action_dim: 6
pred_horizon: 16
obs_horizon: 2
action_horizon: 8

max_steps: 1000

obs_keys: &obs_keys ['joint_values', 'joint_velocities']

env_runner: 
  _target_: imitation.env_runner.robomimic_lowdim_runner.RobomimicEnvRunner
  output_dir: ${output_dir}
  env:
    _target_: imitation.env.pybullet.se2_envs.robot_se2_wrapper.RobotSe2EnvWrapper
    num_obs: 2
    start_pose: [1.0, 0.0, 0.0] # TODO use this!
    target_pose: [0.0, 1.0, 0.0]

policy:
  _target_: imitation.policy.diffusion_policy.DiffusionUnet1DPolicy
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  action_horizon: ${action_horizon}
  num_diffusion_iters: 10
  dataset:
    _target_: imitation.dataset.robomimic_lowdim_dataset.RobomimicLowdimDataset
    dataset_path: ./data/trajs.hdf5
    obs_keys: *obs_keys
    pred_horizon: ${pred_horizon}
    obs_horizon: ${obs_horizon}
    action_horizon: ${action_horizon}
  ckpt_path: ./weights/se2_diffusion_policy.pt


agent:
  _target_: imitation.agent.robomimic_lowdim_agent.RobomimicLowdimAgent