defaults:
  - _self_
  - task: lift_graph
  - policy: graph_diffusion_policy

output_dir: ./outputs
# on evaluating, for environment wrapper
render: False
output_video: True

pred_horizon: 16
obs_horizon: 4
action_horizon: 8
# Training parameters
num_epochs: 2000
val_fraction: 0.1
seed: 0

env_runner: ${task.env_runner}

agent:
  _target_: imitation.agent.robomimic_lowdim_agent.RobomimicLowdimAgent

# Disable evaluation 
# eval_params: "disabled"
max_steps: 500

# Evaluation during training
eval_params:
  eval_every: 1 # evaluate every 50 epochs
  task: ${task}
  policy: ${policy}
  render: False
  output_video: True

  num_episodes: 2
  max_steps: ${max_steps}
  output_dir: ./outputs


  pred_horizon: ${pred_horizon}
  action_horizon: ${action_horizon}
  obs_horizon: ${obs_horizon}


  env_runner: ${task.env_runner}

  seed: 0

  agent: ${agent}