defaults:
  - _self_
  - task: lift_graph
  - policy: graph_diffusion_policy

output_dir: ./output

pred_horizon: 16
obs_horizon: 4
action_horizon: 16

# Training parameters
num_epochs: 1000
seed: 0

env_runner: ${task.env_runner}

agent:
  _target_: imitation.agent.robomimic_lowdim_agent.RobomimicLowdimAgent