_target_: imitation.policy.egnn_policy.EGNNPolicy
node_feature_dim: 1
obs_node_feature_dim: 1
pred_horizon: ${pred_horizon}
obs_horizon: ${obs_horizon}
dataset: ${task.dataset}
ckpt_path: ./weights/${task.task_name}_${task.dataset_type}_egnn_last.pt
lr: 0.0005
batch_size: 128