_target_: imitation.policy.egnn_policy.EGNNPolicy
node_feature_dim: 2
obs_node_feature_dim: 7 # position + quaternion
pred_horizon: ${pred_horizon}
obs_horizon: ${obs_horizon}
dataset: ${task.dataset}
ckpt_path: /home/caio/workspace/GraphDiffusionImitate/weights/${task.task_name}_${task.dataset_type}_egnn_last.pt
lr: 0.0001