_target_: imitation.policy.graph_ddpm_policy.GraphConditionalDDPMPolicy
obs_dim: 7
action_dim: 9
node_feature_dim: 2
num_edge_types: 2 # robot joints, object-robot
pred_horizon: ${pred_horizon}
obs_horizon: ${obs_horizon}
action_horizon: ${action_horizon}
num_diffusion_iters: 200
dataset: ${task.dataset}
denoising_network:
  _target_: imitation.model.graph_diffusion.ConditionalGraphNoisePred
  node_feature_dim: ${policy.node_feature_dim}
  obs_horizon: ${obs_horizon}
  pred_horizon: ${pred_horizon}
  edge_feature_dim: 1
  num_edge_types: ${policy.num_edge_types}
  num_layers: 3
  hidden_dim: 128
ckpt_path: ./weights/diffusion_graph_policy_${task.task_name}_${task.dataset_type}_${task.control_mode}_${policy.num_diffusion_iters}iters.pt
lr: 5e-4
batch_size: 32
