_target_: imitation.policy.mlp_policy.MLPPolicy
obs_dim: ${task.obs_dim}
action_dim: ${task.action_dim}
pred_horizon: ${pred_horizon}
obs_horizon: ${obs_horizon}
action_horizon: ${action_horizon}
model:
  _target_: imitation.model.mlp.MLPNet
  input_dim: ${eval:'${task.obs_dim}*${obs_horizon}'}
  output_dim: ${eval:'${task.action_dim}*${pred_horizon}'}
  hidden_dims: [256, 256, 256, 256]
  activation:
    _target_: torch.nn.LeakyReLU
  output_activation: 
    _target_: torch.nn.Identity
dataset: ${task.dataset}
ckpt_path: ./weights/${task.task_name}_${task.dataset_type}_mlp_last.pt
lr: 0.0001