
task_name: &task_name transport
dataset_type: &dataset_type ph
dataset_path: &dataset_path ./data/${task.task_name}/${task.dataset_type}/low_dim_v141.hdf5

max_steps: ${eval:'1200 if "${task.dataset_type}" == "mh" else 800'}

control_mode: "JOINT_POSITION"

obs_dim: 9
action_dim: 18

robots: &robots ["Panda", "Panda"]

# describe all the objects in the scene
object_state_sizes: &object_state_sizes
  payload_pos: 3
  payload_quat: 4
  trash_pos: 3
  trash_quat: 4
  lid_handle_pos: 3
  lid_handle_quat: 4
  target_bin_pos: 3
  trash_bin_pos: 4
  gripper0_to_payload: 3
  gripper0_to_lid_handle: 3
  gripper1_to_payload: 3
  gripper1_to_trash: 3
  payload_in_target_bin: 1
  trash_in_trash_bin: 1

object_state_keys: &object_state_keys 
  payload: 
    - payload_pos
    - payload_quat
  trash:
    - trash_pos
    - trash_quat
  lid_handle:
    - lid_handle_pos
    - lid_handle_quat

base_link_shift: 
  - [0.0, -0.81, 0.912]
  - [0.0,  0.81, 0.912]
base_link_rotation: 
  - [0.707107, 0, 0, 0.707107]
  - [0.707107, 0, 0, -0.707107]

env_runner: 
  _target_: imitation.env_runner.robomimic_lowdim_runner.RobomimicEnvRunner
  output_dir: ${output_dir}
  action_horizon: ${action_horizon}
  obs_horizon: ${obs_horizon}
  render: ${render}
  output_video: ${output_video}
  env:
    _target_: imitation.env.robomimic_graph_wrapper.RobomimicGraphWrapper
    object_state_sizes: *object_state_sizes
    object_state_keys:  *object_state_keys
    max_steps: ${task.max_steps}
    task: "TwoArmTransport"
    has_renderer: ${render}
    robots: *robots
    output_video: ${output_video}
    control_mode: ${task.control_mode}
    controller_config:
      interpolation: "linear"
      ramp_ratio: 0.2
    base_link_shift: ${task.base_link_shift}
    base_link_rotation: ${task.base_link_rotation}


dataset:
  _target_: imitation.dataset.robomimic_graph_dataset.RobomimicGraphDataset
  dataset_path: ${task.dataset_path}
  robots: *robots
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  object_state_sizes: *object_state_sizes
  object_state_keys: *object_state_keys
  control_mode: ${task.control_mode}
  base_link_shift: ${task.base_link_shift}
  base_link_rotation: ${task.base_link_rotation}