name: run tests

on:
  push:
    branches:
      - master
      - workflow # for testing only

  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: Test random policy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # cache Conda packages to speed up workflow
      - name: Cache Conda packages
        uses: actions/cache@v2
        with:
          path: ~/.conda/pkgs
          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            conda-${{ runner.os }}-

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2  # You can use 'setup-conda' if needed
        with:
          activate-environment: imitation  # Replace with your Conda environment name
          environment-file: conda_environment.yaml  # Specify the environment file if you have one

      - name: Initialize Conda (non-interactive)
        run: conda init --all -v  # Use the '--all' flag to initialize all shells

      - name: Setup robosuite macros
        run: conda activate imitation & python ~/work/GraphDiffusionImitate/GraphDiffusionImitate/src/robosuite/robosuite/scripts/setup_macros.py

      - name: Run test.py
        run: conda run -n imitation python test.py --config-name=test_random_policy